name: PR Workflow

on:
  workflow_dispatch:

  pull_request:
    branches:
      - 'master'

jobs:
  Client-PR-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
        with:
          driver-opts: network=host
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          labels: |
            Maintainer=Paper-Dragon <2678885646@qq.com>
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ifconfig.icu:pr-${{ github.event.pull_request.number }}
