name: PR Workflow

on:
  workflow_dispatch:

  pull_request:
    branches:
      - 'master_python'

jobs:
  Client-PR-Lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          #registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and publish image
        env:
          # fork friendly ^^
          DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/ifconfig.icu:PR
        run: |
          docker buildx build \
          --platform linux/amd64 \
          --label "Maintainer: <Paper-Dragon 2678885646@qq.com>" \
          --push \
          -t ${DOCKER_REPO} \
          -f Dockerfile \
          .
