name: Update Submodules

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        # with:
        #   submodules: recursive

      - name: Update GeoLite.mmdb Submodule
        run: |
          git submodule update --init || true
          cd GeoLite.mmdb
          git fetch origin || true
          git reset --hard origin/download || (echo "Failed to reset to 'origin/download'" && exit 1)
          cd ..
          git config --local user.email "2678885646@qq.com"
          git config --local user.name "PaperDragon-bot"
          git add GeoLite.mmdb
          git commit -m "Update GeoLite.mmdb submodule to latest 'download' branch" || echo "No changes to commit"
      
      - name: Push changes
        run: |
          git branch -a
          git status 
          if [ -n "${{ github.event.pull_request }}" ]; then
            git push origin ${{ github.head_ref }}
          else
            git push origin
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


