name: Update Submodules

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Update Submodules to Remote Only
        run: |
          git submodule foreach --recursive '
            git fetch origin
            git reset --hard origin/$(git branch --show-current)
          '
          git add .
          git commit -m "Update submodules to latest remote" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
