name: Update Submodules

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Update GeoLite.mmdb Submodule
        run: |
          git submodule update --init --recursive
          cd GeoLite.mmdb
          git fetch origin download
          git checkout download || (echo "Branch 'download' not found" && exit 1)
          git reset --hard origin/download
          cd ..
          git add GeoLite.mmdb
          git commit -m "Update GeoLite.mmdb submodule to latest 'download' branch" || echo "No changes to commit"
          git push origin || echo "No changes to push"
