name: Update Submodules

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Update Submodules to Remote Only
        run: |
          cd GeoLite.mmdb
          git reset --hard origin/download
          cd ..
          git commit -m "Update Submodule"
          git push origin
